/* 
    Creado por Alejandro Venegas Robles. 
    En caso de incidencias, contactar con alejandro2196vr@gmail.com 
*/

// CSV Content (Pre-parsed to ensure offline compatibility)
const rawCsvData = [
    { type: "Diagnostico", terms: "insuficiencia cardiaca|ic|falla cardiaca|descompensacion cardiaca|anasarca cardiaca|cor pulmonale agudo|congestion venosa|ic descompensada", alert: "Requiere 3 apellidos obligatorios: Temporalidad, Fracción de eyección y Etiología. No use \'descompensación\'.", text: "Insuficiencia cardiaca [Aguda / Crónica / Crónica agudizada] con fracción de eyección [Sistólica / Diastólica / Combinada] secundaria a [Etiología].", code: "I50.-", tree: true },
    { type: "Diagnostico", terms: "endocarditis|infeccion valvular|endocarditis infecciosa|ei|endocarditis bacteriana|vegetacion valvular infecciosa", alert: "Diagnóstico de alta complejidad. Requiere especificar agudeza, válvula afectada (nativa/protésica) y microorganismo.", text: "Endocarditis [Aguda / Subaguda] de válvula [Aórtica / Mitral / Tricúspide] [Nativa / Protésica] por [Microorganismo].", code: "I33.0", tree: true },
    { type: "Diagnostico", terms: "fibrilacion auricular|fa|arritmia|fa rapida|arritmia completa por fa", alert: "Es imperativo especificar el patrón temporal de la arritmia para una correcta asignación de comorbilidad.", text: "Fibrilación auricular [Paroxística / Persistente / Crónica-Permanente].", code: "I48.-", tree: true },
    { type: "Diagnostico", terms: "neumonia|infeccion respiratoria|bronconeumonia|ir|nac|nih|nnosocomial|bronconeumonia bilateral|condensacion pulmonar infecciosa", alert: "Evite \'Infección Respiratoria\' de forma aislada. Asocie el patógeno causal (incluso empírico) y documente si hay insuficiencia respiratoria aguda.", text: "Neumonía probable por [Germen], asociada a Insuficiencia Respiratoria Aguda [Hipoxémica / Hipercápnica].", code: "J12-J18", tree: true },
    { type: "Diagnostico", terms: "epoc|exacerbacion epoc|agudizacion epoc|broncoespasmo|aepoc|epoc agudizado|broncoespasmo severo epoc", alert: "Documente \'EPOC con exacerbación aguda\'. Evite \'broncoespasmo\' como diagnóstico principal. Especifique si hay Cor pulmonale.", text: "Enfermedad Pulmonar Obstructiva Crónica con exacerbación aguda [y Cor Pulmonale].", code: "J44.1", tree: false },
    { type: "Diagnostico", terms: "tep|tromboembolismo pulmonar|embolia pulmonar|tep masivo|tep submasivo|tromboembolismo pulmonar agudo|embolismo pulmonar|infarto pulmonar", alert: "Patología de altísima complejidad. Especifique si cursa con Cor Pulmonale agudo.", text: "Tromboembolismo pulmonar agudo [con / sin] Cor Pulmonale agudo.", code: "I26.-", tree: true },
    { type: "Diagnostico", terms: "sepsis|bacteriemia|shock septico|infeccion grave|sospecha de sepsis|sepsis de origen|sepsis respiratoria|bacteriemia por", alert: "La palabra \'Sepsis\' dispara el Nivel de Severidad (SOI). Si cumple criterios (qSOFA/SOFA), documente \'Sepsis de origen X\' explícitamente.", text: "Sepsis de origen [Urinario / Respiratorio / Biliar / Abdominal / Catéter / Desconocido].", code: "A41.- / R65.2-", tree: true },
    { type: "Diagnostico", terms: "itu|infeccion urinaria|bacteriuria|sepsis urinaria|urosepsis|pielonefritis aguda|pna|cistitis|prostatitis aguda|infeccion urinaria complicada", alert: "PELIGRO: \'Urosepsis\' suele decodificarse como ITU genérica. Si hay afectación sistémica, use \"Sepsis de origen urinario\". Si no, especifique \"Pielonefritis aguda\".", text: "[Sepsis de origen urinario / Pielonefritis aguda / Prostatitis aguda] secundaria a [Microorganismo].", code: "N39.0 / N15.9", tree: true },
    { type: "Diagnostico", terms: "celulitis|infeccion partes blandas|erisipela|dermoepidermitis|ipb|fascitis", alert: "Evite \'Celulitis\' sin topografía. Documente la localización anatómica exacta para evitar un código residual.", text: "Celulitis y absceso de [Miembro Inferior / Miembro Superior / Tronco] [Derecho / Izquierdo].", code: "L03.-", tree: true },
    { type: "Diagnostico", terms: "hta|hipertension|crisis hipertensiva|emergencia hipertensiva|urgencia hipertensiva|encefalopatia hipertensiva", alert: "La HTA esencial no eleva la severidad. Documente la afectación de órgano diana (Corazón/Riñón/Cerebro) para codificar cardiopatía o nefropatía hipertensiva.", text: "Enfermedad [Cardíaca / Cardiorrenal / Renal] hipertensiva con [Insuficiencia Cardiaca / ERC estadio X].", code: "I11-I15", tree: true },
    { type: "Diagnostico", terms: "daño renal|fracaso renal|ira|insuficiencia renal aguda|lra|lesion renal aguda|nta|necrosis tubular aguda|fallo renal agudo|fracaso renal oligurico", alert: "Documente \'Fracaso Renal Agudo\'. Especifique \'Necrosis Tubular Aguda\' si procede. Evite \'deterioro de la función renal\'.", text: "Fracaso Renal Agudo [secundario a Necrosis Tubular Aguda / prerrenal / obstructivo].", code: "N17.-", tree: true },
    { type: "Diagnostico", terms: "hiponatremia|hiperpotasemia|desequilibrio electrolitico|hiponatremia grave|hiperkaliemia|hipokaliemia|hiperpotasemia severa", alert: "No olvide codificar los trastornos iónicos severos si requirieron tratamiento, impactan en la complejidad del caso.", text: "[Hiponatremia / Hiperpotasemia / Hipopotasemia] severa con necesidad de reposición activa.", code: "E87.1 / E87.5", tree: true },
    { type: "Diagnostico", terms: "diabetes descompensada|cad|ehh|cetoacidosis|hipoglucemia|cetoacidosis diabetica|estado hiperosmolar|coma diabetico|hipoglucemia severa", alert: "No use \'diabetes descompensada\'. Especifique la complicación aguda exacta que motivó o complicó el ingreso.", text: "Diabetes Mellitus tipo [1 / 2] con [Cetoacidosis / Estado Hiperosmolar / Hipoglucemia severa].", code: "E08-E13", tree: true },
    { type: "Diagnostico", terms: "hemorragia digestiva|hda|hdb|melenas|rectorragia|sangrado digestivo|hematemesis|hematoquecia|ulcus sangrante", alert: "Melenas es un síntoma. Diagnostique la topografía y, si es posible, la etiología (varicosa vs no varicosa).", text: "Hemorragia Digestiva [Alta / Baja] de origen [Varicoso / No Varicoso / Indeterminado].", code: "K92.2 / K25-K28", tree: true },
    { type: "Diagnostico", terms: "cirrosis|hepatopatia|insuficiencia hepatica basica|descompensacion ascitica|ascitis a tension|encefalopatia portal|pbe|peritonitis bacteriana espontanea", alert: "La \'hepatopatía\' es basal. Si hay descompensación, indíquelo explícitamente junto con sus manifestaciones (Ascitis, Encefalopatía, PBE).", text: "Cirrosis hepática descompensada con [Ascitis / Encefalopatía hepática / Peritonitis Bacteriana Espontánea].", code: "K74.- / K70.3", tree: true },
    { type: "Diagnostico", terms: "colecistitis|colangitis|patologia biliar|colecistitis aguda|piocolecisto|colangitis aguda|sepsis biliar", alert: "Diferencie claramente colecistitis de colangitis e indique si hay obstrucción.", text: "[Colecistitis / Colangitis] aguda [con / sin] obstrucción biliar.", code: "K81.- / K83.0-", tree: true },
    { type: "Diagnostico", terms: "encefalopatia|bajo nivel de conciencia|estupor|coma|coma metabolico|encefalopatia uremica|encefalopatia hipercapnica|estupor metabolico", alert: "Evite usar \'bajo nivel de conciencia\' (es un síntoma). Documente la etiología subyacente de la encefalopatía.", text: "Encefalopatía [Metabólica / Hepática / Urémica / Tóxica / Hipóxica / Hipercápnica].", code: "G93.4-", tree: true },
    { type: "Diagnostico", terms: "ictus|acv|accidente cerebrovascular|infarto cerebral|acv isquemico|acv hemorragico|hemorragia intraparenquimatosa|ait", alert: "La CIE-10 exige diferenciar entre isquémico y hemorrágico, y la arteria afectada si se conoce por neuroimagen.", text: "Ictus [Isquémico / Hemorrágico] en territorio de arteria [Cerebral Media / Anterior / Posterior / Basilar].", code: "I63.- / I61.-", tree: true },
    { type: "Diagnostico", terms: "delirium|sca|sindrome confusional|desorientacion|agitacion|sindrome confusional agudo|delirium tremens|agitacion psicomotriz|encefalopatia toxico-metabolica", alert: "Evite usar síntomas aislados como \'desorientación\' o \'agitación\'. Diagnostique la entidad orgánica: \'Delirium\' o \'SCA\'.", text: "[Delirium / Síndrome Confusional Agudo] [Hipoactivo / Hiperactivo / Mixto].", code: "F05", tree: true },
    { type: "Diagnostico", terms: "desnutricion|malnutricion|malnutricion calorico-proteica|desnutricion severa", alert: "Impacto altísimo en el GDR. Especifique siempre el grado (Leve, Moderada, Severa calórico-proteica).", text: "Desnutrición calórico-proteica [Leve / Moderada / Severa].", code: "E43 / E44.-", tree: true },
    { type: "Diagnostico", terms: "anemia|sindrome anemico|bajada de hb|anemia cronica|anemia severa|anemia sintomatica|anemia hemolitica|ahai|anemia ferropenica|sangrado activo", alert: "No use \'Anemia\' inespecífica. Para la Unidad, clasifique la etiología etiopatogénica exacta.", text: "Anemia [Hemolítica Autoinmune / Ferropénica / por Trastorno Crónico / Aplásica / Aguda Posthemorrágica].", code: "D50-D64", tree: true },
    { type: "Diagnostico", terms: "nefritis lupica|nefropatia lupica|afectacion renal lupus|brote de nefritis lupica|recaida nefritis lupica|empeoramiento funcion renal lupus|brote lupico renal|glomerulonefritis lupica activa|sedimento activo lupus", alert: "Máxima severidad. Especifique la clase histológica (I-VI) si se dispone de biopsia y tipifique el grado de insuficiencia renal aguda o crónica.", text: "Nefritis lúpica clase [I-VI] con [Fracaso Renal Agudo / ERC estadio X].", code: "M32.14 / M32.15", tree: true },
    { type: "Diagnostico", terms: "neurolupus|lupus neurologico|psicosis lupica|mielitis lupica|cerebritis lupica|convulsiones lupus|brote de neurolupus|psicosis lupica aguda|brote neurologico lupus|estado confusional lupico", alert: "El término \'neurolupus\' es informal. Defina la manifestación neuropsiquiátrica exacta (cerebritis, mielitis, psicosis, convulsiones) para la CIE-10.", text: "Lupus eritematoso sistémico con afectación del sistema nervioso central tipo [Psicosis / Convulsiones / Mielitis transversa / Cerebritis].", code: "M32.19", tree: true },
    { type: "Diagnostico", terms: "neumonitis lupica|hemorragia alveolar lupus|afectacion pulmonar lupus|brote pulmonar lupico|capilaritis lupica|neumonitis lupica aguda|pulmon encogido", alert: "Complicación potencialmente letal. Diferencie neumonitis aguda de hemorragia alveolar difusa (capilaritis).", text: "Lupus eritematoso sistémico con afectación pulmonar tipo [Neumonitis aguda / Hemorragia alveolar difusa].", code: "M32.13", tree: true },
    { type: "Diagnostico", terms: "brote lupico|brote de lupus|les|lupus eritematoso sistemico|lupus articular|lupus cutaneo|recaida lupica|lupus activo|reactivacion lupus|lupus eritematoso diseminado|brote poliarticular lupico", alert: "No use \'brote\' de forma aislada. Si la afectación es menor (cutáneo-articular), especifíquelo. Si hay daño orgánico mayor, use el término de dicho órgano.", text: "Lupus eritematoso sistémico con afectación [Articular / Cutánea / Hematológica].", code: "M32.9", tree: true },
    { type: "Diagnostico", terms: "saf|sindrome antifosfolipido|saf catastrofico|anticuerpos antifosfolipidos|brote de saf|trombosis por saf|microangiopatia trombotica saf|sindrome antifosfolipidico|caps|evento trombotico por saf", alert: "Diferencie SAF primario de secundario (asociado a LES). Si cursa con fracaso multiorgánico microtrombótico, documente explícitamente \'SAF Catastrófico\'.", text: "Síndrome antifosfolípido [Primario / Secundario] con [Trombosis venosa / Trombosis arterial / SAF Catastrófico].", code: "D68.61 / D68.62", tree: true },
    { type: "Diagnostico", terms: "crisis renal esclerodermica|fallo renal esclerodermia|crisis esclerodermica|brote renal esclerodermia|hta maligna esclerodermia", alert: "Emergencia médica. Documente explícitamente el daño renal asociado y la emergencia hipertensiva si coexiste.", text: "Crisis renal esclerodérmica con fracaso renal agudo [y emergencia hipertensiva].", code: "M34.0 + N17.9", tree: false },
    { type: "Diagnostico", terms: "epi esclerodermia|afectacion pulmonar esclerodermia|hap esclerodermia|empeoramiento epi esclerodermia|fibrosis pulmonar esclerodermia|brote alveolitis esclerodermia|cor pulmonale esclerodermia", alert: "Separe la enfermedad pulmonar intersticial (EPI) de la hipertensión arterial pulmonar (HAP), ya que modifican el pronóstico y el GDR.", text: "Esclerosis sistémica con [Enfermedad Pulmonar Intersticial / Hipertensión Arterial Pulmonar].", code: "M34.81", tree: true },
    { type: "Diagnostico", terms: "esclerodermia|esclerosis sistemica|crest|brote cutaneo esclerodermia|esclerosis sistemica progresiva|crisis raynaud severa", alert: "Para ingresos basales, especifique el subtipo dermatológico si no hay crisis visceral aguda.", text: "Esclerosis sistémica [Cutánea difusa / Cutánea limitada].", code: "M34.9", tree: true },
    { type: "Diagnostico", terms: "sindrome antisintetasa|antisintetasa|jo1|brote antisintetasa|recaida sindrome antisintetasa|jo-1 positivo activo", alert: "Entidad de alta morbimortalidad. Asocie siempre la presencia de EPI o miopatía severa.", text: "Síndrome Antisintetasa con [Enfermedad Pulmonar Intersticial / Miopatía inflamatoria].", code: "M33.2- / M33.1-", tree: true },
    { type: "Diagnostico", terms: "miositis|dermatomiositis|polimiositis|miopatia inflamatoria|miopatia necrotizante|brote de miositis|recaida polimiositis|brote dermatomiositis|debilidad muscular miositis|empeoramiento miopatia inflamatoria|miopatia necrotizante activa", alert: "El término miopatía es inespecífico. Defina el subtipo y la afectación extramuscular (bulbar, respiratoria).", text: "[Dermatomiositis / Polimiositis / Miopatía necrotizante] con afectación [Muscular proximal / Bulbar / Respiratoria].", code: "M33.-", tree: true },
    { type: "Diagnostico", terms: "sjogren|sindrome de sjogren|sicca|sjogren extraglandular|neuropatia sjogren|epi sjogren|nefritis sjogren|brote sistemico sjogren|vasculitis por sjogren|brote extraglandular sjogren", alert: "Diferencie primario de secundario. Documente si existe afectación extraglandular (neurológica, pulmonar, renal) para evitar el código de sicca simple.", text: "Síndrome de Sjögren [Primario / Secundario] con afectación extraglandular tipo [Neuropatía periférica / EPI / Nefritis].", code: "M35.0-", tree: true },
    { type: "Diagnostico", terms: "wegener|gpa|granulomatosis con poliangeitis|brote de wegener|recaida wegener|gnrp wegener|brote de gpa", alert: "Use la nomenclatura actual (GPA) y detalle la afectación destructiva ORL, pulmonar o renal.", text: "Granulomatosis con poliangeítis (GPA) con afectación [Renal / Pulmonar / Vía aérea superior].", code: "M31.3-", tree: true },
    { type: "Diagnostico", terms: "pam|poliangeitis microscopica|churg strauss|egpa|vasculitis anca|brote pam|gnrp pam|brote vasculitis anca|recaida vasculitis|brote de vasculitis|hemorragia alveolar vasculitis|gnrp", alert: "Tipifique el tipo de vasculitis ANCA y el órgano diana en fracaso agudo.", text: "Vasculitis asociada a ANCA tipo [PAM / EGPA] con afectación [Renal / Pulmonar / Neurológica].", code: "M31.7 / M30.1", tree: true },
    { type: "Diagnostico", terms: "arteritis de celulas gigantes|arteritis de la temporal|recaida arteritis de la temporal|brote isquemico celulas gigantes|polimialgia reumatica activa", alert: "Especifique si existen complicaciones isquémicas agudas (neuropatía óptica isquémica, claudicación mandibular).", text: "Arteritis de Células Gigantes [con / sin] neuropatía óptica isquémica.", code: "M31.5 / M31.6", tree: true },
    { type: "Diagnostico", terms: "sdra|distres respiratorio|sindrome de distres respiratorio agudo|distres|distres pulmonar", alert: "Complicación mayor. No lo confunda documentalmente con \'insuficiencia respiratoria\'. Especifique la etiología desencadenante.", text: "Síndrome de Distrés Respiratorio Agudo (SDRA) secundario a [Etiología].", code: "J80", tree: false },
    { type: "Diagnostico", terms: "eap|edema agudo de pulmon|edema pulmonar agudo|pulmon de shock", alert: "Diferencie si es cardiogénico (I50.1) o no cardiogénico (J81.0, requiere etiología: tóxicos, altura, yatrogenia hídrica).", text: "Edema Agudo de Pulmón [Cardiogénico / No Cardiogénico secundario a...].", code: "I50.1 / J81.0", tree: true },
    { type: "Diagnostico", terms: "shock cardiogenico|shock hipovolemico|shock hemorragico|shock anafilactico|paciente en shock", alert: "Tipifique siempre la etiología hemodinámica del shock. \'Paciente en shock\' asigna un código inespecífico de bajo peso.", text: "Shock [Cardiogénico / Hipovolémico / Hemorrágico / Anafiláctico].", code: "R57.- / T78.2", tree: true },
    { type: "Diagnostico", terms: "cid|coagulacion intravascular diseminada|desfibrinacion|sris no infeccioso|sindrome de respuesta inflamatoria sistemica", alert: "Para el SRIS no infeccioso (ej. pancreatitis, trauma), especifique si asocia o no disfunción orgánica aguda. Escriba explícitamente \'CID\'.", text: "[Coagulación Intravascular Diseminada (CID) / Síndrome de Respuesta Inflamatoria Sistémica (SRIS) de origen no infeccioso con disfunción orgánica aguda].", code: "D65 / R65.1-", tree: true },
    { type: "Diagnostico", terms: "acidosis lactica|hiperlactacidemia severa|slt|sindrome de lisis tumoral|tormenta tiroidea|crisis tirotoxica|coma mixedematoso", alert: "Entidades metabólicas de severidad extrema. Tienen códigos independientes que multiplican la complejidad (SOI 3 o 4).", text: "[Acidosis Láctica / Síndrome de Lisis Tumoral / Tormenta Tiroidea / Coma Mixedematoso].", code: "E87.2 / E88.3 / E03.5", tree: true },
    { type: "Diagnostico", terms: "falla hepatica aguda|insuficiencia hepatica aguda|fha|aclf|fallo hepatico fulminante", alert: "Evite \'empeoramiento de enzimas\'. Especifique si es Insuficiencia Hepática Aguda o ACLF (Insuficiencia hepática aguda sobre crónica).", text: "[Insuficiencia Hepática Aguda (FHA) / Insuficiencia Hepática Aguda sobre Crónica (ACLF)].", code: "K72.0-", tree: true },
    { type: "Diagnostico", terms: "isquemia mesenterica|infarto intestinal|isquemia intestinal", alert: "Isquemia Mesentérica (delgada o gruesa) es una complicación mayor. Documente anatómicamente el infarto/isquemia.", text: "Isquemia mesentérica aguda de [intestino delgado / colon].", code: "K55.0-", tree: true },
    { type: "Diagnostico", terms: "status epileptico|estado epileptico|estatus convulsivo|edema cerebral|herniacion cerebral|enclavamiento cerebral", alert: "Descriptores neurocríticos de inminencia de muerte que elevan el Riesgo de Mortalidad (ROM). Documentarlos explícitamente.", text: "[Status epiléptico / Edema cerebral / Herniación del encéfalo] secundario a [Etiología].", code: "G41.- / G93.6", tree: true },
    { type: "Diagnostico", terms: "retencion aguda de orina|rao|globo vesical|anuria obstructiva|retencion urinaria|obstruccion urinaria baja", alert: "La RAO es un síntoma. Especifique la causa (ej. HBP, fármacos) y documente SIEMPRE si ha provocado \'Fracaso Renal Agudo obstructivo\', lo cual eleva drásticamente la severidad.", text: "Retención aguda de orina secundaria a [HBP / Fármacos / Causa neurológica] [con / sin] Fracaso Renal Agudo postrenal.", code: "R33.9 / N17.9", tree: true },
    { type: "Diagnostico", terms: "asma|crisis asmatica|estatus asmatico|brote asmatico|broncoespasmo asmatico|exacerbacion asma", alert: "Evite \'crisis asmática\' inespecífica. Para capturar severidad extrema, documente \'Estado asmático\' (Status asthmaticus) si hay refractariedad clínica o distrés respiratorio.", text: "Asma [intermitente / persistente] con [Exacerbación aguda / Estado Asmático].", code: "J45.-", tree: true },
    { type: "Diagnostico", terms: "erc agudizada|empeoramiento funcion renal|aki on ckd|fracaso renal sobre cronico|reagudizacion insuficiencia renal", alert: "Impacto doble en el GDR. Requiere documentar obligatoriamente ambos estadios: el Fracaso Renal Agudo (N17.9) y el estadio basal crónico.", text: "Fracaso Renal Agudo [prerrenal / NTA] sobre Enfermedad Renal Crónica estadio [1-5].", code: "N17.9 + N18.-", tree: true },
    { type: "Diagnostico", terms: "pancreatitis|pancreatitis aguda|brote de pancreatitis|inflamacion pancreatica", alert: "Detalle la etiología (biliar, alcohólica, idiopática). Es vital documentar si hay necrosis, infección o SRIS asociado para elevar la complejidad al máximo.", text: "Pancreatitis aguda [Biliar / Alcohólica / Idiopática] [sin / con] necrosis [estéril / infectada].", code: "K85.-", tree: true },
    { type: "Diagnostico", terms: "diarrea por c diff|clostridium|clostridioides|colitis pseudomembranosa|toxina c diff|diarrea nosocomial", alert: "Diagnóstico de muy alto impacto hospitalario. Diferencie entre enterocolitis simple y la forma severa con pseudomembranas.", text: "Enterocolitis por Clostridioides difficile [con / sin] colitis pseudomembranosa.", code: "A04.7-", tree: true },
    { type: "Diagnostico", terms: "gota|brote de gota|artritis gotosa|podagra|pseudogota|condrocalcinosis|ataque de gota", alert: "Especifique la articulación afectada y si es una forma idiopática o inducida (ej. por diuréticos, insuficiencia renal).", text: "Artritis gotosa aguda [idiopática / secundaria] en [Articulación].", code: "M10.-", tree: true },
    { type: "Diagnostico", terms: "traqueobronquitis|bronquitis aguda|infeccion respiratoria de vias bajas|infeccion respiratoria no consolidativa|irva|catarro bronquial", alert: "Evite \'infección respiratoria\' inespecífica (bajo peso). Si no hay neumonía, diagnostique \'Bronquitis aguda\' o \'Traqueobronquitis\' y asocie el virus/bacteria causal si se conoce.", text: "[Bronquitis aguda / Traqueobronquitis aguda] secundaria a [Microorganismo / Virus no tipificado].", code: "J20.-", tree: true },
    { type: "Diagnostico", terms: "gripe|influenza|virus de la gripe|infeccion por virus influenza|gripe a|gripe b|sindrome gripal", alert: "No use \'síndrome gripal\'. Especifique si cursa con neumonía u otras manifestaciones respiratorias severas, y tipifique el virus (A, B, no tipificado).", text: "Gripe por virus [A / B / no identificado] con [Neumonía / Otras manifestaciones respiratorias / Manifestaciones digestivas].", code: "J09-J11", tree: true },
    { type: "Diagnostico", terms: "vrs|virus respiratorio sincitial|infeccion por vrs|bronquiolitis por vrs|neumonia por vrs", alert: "En el adulto mayor, el VRS impacta significativamente la complejidad. Especifique si la infección se manifiesta como Neumonía o como Bronquitis aguda.", text: "[Neumonía / Bronquitis aguda / Infección respiratoria baja] por Virus Respiratorio Sincitial (VRS).", code: "B97.4 / J12.1", tree: true },
    { type: "Diagnostico", terms: "covid|covid-19|sars-cov-2|infeccion por coronavirus|coronavirus|neumonia covid", alert: "El código U07.1 es mandatorio. Documente siempre la manifestación clínica severa principal asociada al virus para que el agrupador la capture.", text: "Enfermedad por COVID-19 con [Neumonía viral / SDRA / Sin complicaciones respiratorias mayores].", code: "U07.1", tree: true },
    { type: "Diagnostico", terms: "ulceras por presion|upp|escara|ulcera sacra|ulcera de talon|escara necrotica", alert: "Las UPP son un medidor de calidad y complejidad. Es OBLIGATORIO especificar la localización anatómica exacta y el Estadio (I, II, III, IV o Inclasificable).", text: "Úlcera por presión en [Localización anatómica] de estadio [I / II / III / IV / Inclasificable].", code: "L89.-", tree: true },
    { type: "Diagnostico", terms: "elevacion de troponinas|curva de troponinas|daño miocardico|iam tipo 2|infarto tipo 2|isquemia miocardica|troponinas positivas", alert: "Evite \'elevación de troponinas\'. Si hay isquemia por desbalance demanda/aporte (ej. sepsis, anemia, FA rápida), diagnostique explícitamente \'Infarto Agudo de Miocardio Tipo 2\'.", text: "Infarto Agudo de Miocardio Tipo 2 secundario a [Sepsis / Anemia / Taquiarritmia / Hipoxemia].", code: "I21.A1", tree: true },
    { type: "Diagnostico", terms: "pancitopenia|neutropenia|bajada de defensas|aplasia medular|citopenia|leucopenia|agranulocitosis", alert: "Documente la línea celular exacta afectada. Especifique si es secundaria a fármacos (quimioterapia, antibióticos) o a un proceso infeccioso/autoinmune.", text: "[Pancitopenia / Neutropenia severa / Agranulocitosis] secundaria a [Fármaco / Infección / Etiología].", code: "D61.81- / D70.-", tree: true },
    { type: "Diagnostico", terms: "ileo paralitico|obstruccion intestinal|suboclusion intestinal|ileo adinamico|oclusion intestinal", alert: "No lo deje solo en la evolución clínica. Páselo a diagnósticos al alta, indicando si es íleo paralítico (metabólico/farmacológico) u obstrucción mecánica.", text: "[Íleo paralítico / Obstrucción intestinal mecánica] secundaria a [Causa].", code: "K56.0", tree: true },
    { type: "Diagnostico", terms: "infeccion de via|infeccion de cateter|bacteriemia asociada a cateter|brc|cautin|sepsis por via", alert: "Requiere un código específico de complicación de dispositivo. Especifique siempre el microorganismo y el tipo de vía anatómica (CVC, PICC, periférica).", text: "Infección del torrente sanguíneo asociada a catéter venoso [Central / Periférico] por [Germen].", code: "T80.211-", tree: true },
    { type: "Diagnostico", terms: "obesidad morbida|obesidad severa|imc mayor 40|obesidad extrema|gran obesidad", alert: "La obesidad mórbida (IMC > 40) es una comorbilidad basal mayor que justifica el aumento de recursos y estancias de enfermería. Documente siempre el IMC.", text: "Obesidad mórbida con Índice de Masa Corporal (IMC) mayor de 40.", code: "E66.01", tree: false },
    { type: "Diagnostico", terms: "abstinencia alcoholica|delirium tremens|mono de alcohol|deprivacion alcoholica|sindrome de abstinencia", alert: "Diferencie el síndrome de abstinencia simple del Delirium Tremens. Este último tiene un altísimo peso de severidad y mortalidad (ROM).", text: "Síndrome de abstinencia alcohólica [con / sin] Delirium Tremens.", code: "F10.231", tree: true },
    { type: "Diagnostico", terms: "fiebre|sindrome febril|fod|fiebre sin foco|fiebre de origen desconocido|pico febril", alert: "La fiebre aislada es un síntoma de muy bajo peso (Código R). Si no encuentra el foco, especifique SIEMPRE si ocurre en un paciente con inmunosupresión o neutropenia, lo cual eleva la severidad.", text: "[Fiebre de origen desconocido / Fiebre en paciente inmunodeprimido / Fiebre en paciente neutropénico].", code: "R50.-", tree: true },
    { type: "Diagnostico", terms: "bacteriemia|hemocultivos positivos|bacteriemia primaria|bacteriemia sin foco", alert: "Una \'bacteriemia\' es un hallazgo de laboratorio que no eleva el peso tanto como una infección clínica. Evalúe y documente \'Sepsis\' si cumple criterios, o \'Bacteriemia primaria\' si no hay foco evidente.", text: "[Sepsis / Bacteriemia primaria] por [Microorganismo aislado en hemocultivos].", code: "R78.81 / A41.-", tree: true },
    { type: "Diagnostico", terms: "flebitis|flebitis infecciosa|tromboflebitis|infeccion de cateter periferico|infeccion de via periferica", alert: "No use solo \'flebitis\'. Documente si es purulenta/infecciosa y asocie la bacteriemia si los hemocultivos son positivos.", text: "Flebitis y tromboflebitis [purulenta / no purulenta] de vena [periférica / central] secundaria a catéter.", code: "I80.-", tree: true },
    { type: "Diagnostico", terms: "masa|nodulo|tumoracion|lesion ocupante de espacio|loe|neo|lesion sospechosa", alert: "Evite \'masa\' o \'nódulo\' (se codifican como hallazgos inespecíficos). Según su sospecha clínica/radiológica, diagnostique \'Neoplasia maligna\' o \'Neoplasia de comportamiento incierto\'.", text: "Neoplasia [maligna / de comportamiento incierto] de [Órgano y localización anatómica exacta].", code: "C00-D49 / R22.-", tree: true },
    { type: "Diagnostico", terms: "cancer|neoplasia|carcinoma|adenocarcinoma|tumor maligno|sarcoma", alert: "La CIE-10 exige máxima topografía. Especifique si el tumor es primario o secundario (metástasis), y la sublocalización anatómica (ej. lóbulo superior derecho, cabeza de páncreas).", text: "Neoplasia maligna [Primaria / Secundaria] de [Sublocalización anatómica exacta].", code: "C00-C75", tree: true },
    { type: "Diagnostico", terms: "metastasis|enfermedad diseminada|cancer extendido|afectacion metastasica|enfermedad metastasica", alert: "No use el término coloquial \'enfermedad diseminada\'. Debe diagnosticar explícitamente los órganos diana de la metástasis como \'neoplasias malignas secundarias\'.", text: "Neoplasia maligna secundaria de [Hígado / Pulmón / Hueso / Cerebro / Ganglios linfáticos].", code: "C77-C79", tree: true },
    { type: "Diagnostico", terms: "cancer de origen desconocido|cpo|tumor de origen desconocido|neoplasia de origen desconocido|origen primario desconocido", alert: "Entidad con código propio de altísima complejidad clínica (C80.1). Documéntelo de forma exacta junto a las localizaciones metastásicas conocidas.", text: "Neoplasia maligna de origen primario desconocido con metástasis en [Órganos afectados].", code: "C80.1", tree: false },
    { type: "Diagnostico", terms: "insuficiencia respiratoria|ira|ir|insuficiencia respiratoria aguda|insuficiencia respiratoria cronica|insuficiencia respiratoria global|hipoxemia severa|hipercapnia severa|fracaso respiratorio|irca", alert: "Diagnóstico crítico para la severidad. Requiere 2 apellidos OBLIGATORIOS según gasometría/clínica: 1. Temporalidad (Aguda, Crónica, o Crónica agudizada). 2. Mecanismo (Hipoxémica o Hipercápnica).", text: "Insuficiencia respiratoria [Aguda / Crónica / Crónica agudizada] tipo [Hipoxémica / Hipercápnica].", code: "J96.-", tree: true },
    { type: "Diagnostico", terms: "sindrome constitucional|sindrome consuntivo|astenia anorexia y perdida de peso|sindrome de impregnacion|emaciacion", alert: "El \'Síndrome Constitucional\' no existe como entidad codificable de alto peso (se diluye en síntomas). Desglose y documente: \'Pérdida de peso anormal\', \'Caquexia\' o \'Desnutrición [leve/moderada/severa]\' para elevar el peso del episodio.", text: "[Desnutrición severa / Caquexia / Pérdida de peso anormal].", code: "R63.4 / R64", tree: true },
    { type: "Diagnostico", terms: "problematica social|problema social|vive solo|sin red de apoyo|abandono social|incapacidad para autocuidado|anciano fragil|riesgo social", alert: "Los códigos Z de factores sociales no suben la severidad clínica, pero JUSTIFICAN estancias prolongadas ante Gerencia. Especifique: \'Vivir solo\', \'Falta de apoyo familiar\' o \'Incapacidad para el autocuidado\'.", text: "Problema social relacionado con [Vivir solo / Falta de apoyo familiar en el hogar / Incapacidad para autocuidado básico].", code: "Z59.- / Z60.-", tree: true },
    { type: "Diagnostico", terms: "litiasis biliar|colelitiasis|coledocolitiasis|piedras en la vesicula|barro biliar|calculo biliar", alert: "Diferencie colelitiasis (vesícula) de coledocolitiasis (vía principal). Es crítico documentar si asocian complicaciones agudas: Colecistitis, Colangitis o Pancreatitis.", text: "[Colelitiasis / Coledocolitiasis] [con / sin] [Colecistitis aguda / Colangitis aguda / Obstrucción].", code: "K80.-", tree: true },
    { type: "Diagnostico", terms: "caquexia general|caquexia|sindrome consuntivo general|desgaste fisico severo", alert: "Diagnóstico de altísimo impacto nutricional (Código R64). Especifique siempre la enfermedad subyacente si se conoce.", text: "Caquexia secundaria a [Enfermedad subyacente / Desconocida].", code: "R64", tree: true },
    { type: "Diagnostico", terms: "hipopituitarismo|caquexia pituitaria|enfermedad de simmonds|panhipopituitarismo|insuficiencia hipofisaria", alert: "Entidad endocrinológica severa (E23.0). Si asocia caquexia (Enfermedad de Simmonds), documéntelo explícitamente por su alto peso en el Casemix.", text: "Hipopituitarismo con caquexia pituitaria (Enfermedad de Simmonds).", code: "E23.0", tree: false },
    { type: "Diagnostico", terms: "sindrome de emaciacion por vih|emaciacion vih|wasting syndrome vih|caquexia por vih|desnutricion vih", alert: "Complicación definitoria de SIDA (B22.2). Modifica drásticamente la categoría de complejidad del paciente infectado por VIH.", text: "Síndrome de emaciación asociado a enfermedad por virus de la inmunodeficiencia humana (VIH).", code: "B22.2", tree: false },
    { type: "Diagnostico", terms: "marasmo nutricional|marasmo|desnutricion calorico-proteica severa con marasmo", alert: "La forma más grave de desnutrición calórica (E41). Suba la severidad clínica al máximo documentando el término \'Marasmo\'.", text: "Marasmo nutricional (Desnutrición calórico-proteica severa).", code: "E41", tree: false },
    { type: "Diagnostico", terms: "tumor maligno asociado con caquexia|caquexia tumoral|caquexia neoplastica|caquexia oncologica", alert: "No ponga solo \'caquexia\' si el paciente tiene cáncer. \'Caquexia tumoral\' tiene un código combinado específico de muy alta complejidad (C80.2).", text: "Tumor maligno asociado con caquexia tumoral.", code: "C80.2", tree: false },
    { type: "Procedimiento", terms: "colecistostomia|drenaje biliar|drenaje vesicula", alert: "Impacto quirúrgico altísimo. Documente el abordaje percutáneo y que se dejó catéter/dispositivo in situ.", text: "Drenaje percutáneo de vesícula biliar con dispositivo de drenaje tubular.", code: "0FB43ZZ", tree: false },
    { type: "Procedimiento", terms: "drenaje absceso|puncion absceso|radiologia intervencionista absceso", alert: "Especifique localización anatómica exacta y si se dejó catéter de drenaje para asegurar el código de intervención.", text: "Drenaje percutáneo de absceso en [Hígado / Cavidad Abdominal / Psoas / Retroperitoneo] con dispositivo de drenaje.", code: "0W9...", tree: true },
    { type: "Procedimiento", terms: "vmni|bipap|cpap|ventilacion no invasiva|ventilacion mecanica", alert: "Parámetro crítico. Documente obligatoriamente el umbral de duración (más o menos de 96 horas ininterrumpidas).", text: "Asistencia respiratoria no invasiva [menor de 96 horas / mayor de 96 horas] consecutivas.", code: "5A09...", tree: true },
    { type: "Procedimiento", terms: "toracocentesis|pleurocentesis|drenaje pleural|puncion pleural", alert: "Especifique 3 ejes obligatorios para CIE-10-PCS: 1. Lateralidad (Der/Izq). 2. Fin (Diagnóstico/Terapéutico). 3. Dispositivo (Punción simple vs Tubo de drenaje dejado in situ).", text: "Drenaje percutáneo de cavidad pleural [Derecha / Izquierda] con fines [Diagnósticos / Terapéuticos]. Dispositivo: [Ninguno / Tubo de drenaje].", code: "0W993ZZ", tree: true },
    { type: "Procedimiento", terms: "paracentesis|drenaje ascitico|puncion ascitica", alert: "Especifique si se dejó catéter de drenaje in situ y el fin (Diagnóstico o Terapéutico).", text: "Drenaje percutáneo de cavidad peritoneal con fines [Diagnósticos / Terapéuticos]. Dispositivo: [Ninguno / Catéter].", code: "0W9G3ZZ", tree: true },
    { type: "Procedimiento", terms: "artrocentesis|puncion articular|drenaje articular", alert: "Especifique la articulación exacta (ej. rodilla derecha) y el fin del procedimiento.", text: "Drenaje percutáneo de articulación [Especificar].", code: "0R9... / 0S9...", tree: false },
    { type: "Procedimiento", terms: "puncion lumbar|extraccion lcr|puncion espinal|raquicentesis|pl", alert: "Procedimiento invasivo de alto impacto. La CIE-10-PCS exige especificar obligatoriamente si el objetivo de la extracción de LCR fue Diagnóstico (análisis) o Terapéutico (ej. aliviar presión intracraneal).", text: "Drenaje percutáneo de canal espinal con fines [Diagnósticos / Terapéuticos]. Dispositivo: Ninguno.", code: "009U3ZZ", tree: true },
    { type: "Procedimiento", terms: "via central|cvc|picc|cateter venoso|drum", alert: "Impacto directo en la complejidad. Especifique siempre el abordaje percutáneo y la vena exacta canulada.", text: "Inserción percutánea de dispositivo de infusión en vena central [Yugular / Subclavia / Cava Superior / Basílica / Cefálica].", code: "02HV33Z", tree: true },
    { type: "Procedimiento", terms: "cardioversion|choque electrico", alert: "Procedimiento de alto impacto. Especifique si fue farmacológica o eléctrica.", text: "Cardioversión [Eléctrica / Farmacológica] de ritmo cardíaco.", code: "5A2204Z", tree: true },
    { type: "Procedimiento", terms: "pet|pet-tc|pet tc|tomografia por emision de positrones", alert: "Para contabilidad analítica y justificación de estancias: Especifique localización y el radiofármaco utilizado (ej. FDG).", text: "Tomografía por emisión de positrones (PET-TC) de [Cuerpo entero / Tórax / Cerebro] con [Fluorodeoxiglucosa 18F / Otro radiofármaco].", code: "C...", tree: true },
    { type: "Procedimiento", terms: "tc|tac|tomografia|escaner", alert: "Para contabilidad analítica: Especifique localización anatómica y si se administró contraste IV.", text: "Tomografía computarizada de [Cráneo / Tórax / Abdomen y Pelvis] [con / sin] contraste intravenoso.", code: "B...", tree: true },
    { type: "Procedimiento", terms: "rm|resonancia magnetica|rnm", alert: "Para contabilidad analítica: Especifique localización y administración de contraste paramagnético (Gadolinio).", text: "Resonancia magnética de [Cráneo / Columna / Abdomen] [con / sin] contraste.", code: "B...", tree: true },
    { type: "Procedimiento", terms: "ecocardio|ecocardiograma|ett|ete", alert: "Imprescindible documentar el abordaje de la sonda ultrasónica.", text: "Ecocardiograma [Transtorácico / Transesofágico].", code: "B24...", tree: true },
    { type: "Procedimiento", terms: "cpre|colangiopancreatografia|colangiografia retrograda|esfinterotomia endoscopica|stent biliar|cpre terapeutica|cpre diagnostica", alert: "Procedimiento de alto coste. Especificar siempre la operación raíz realizada durante la endoscopia: ¿Se realizó esfinterotomía, extracción de cálculos o inserción de endoprótesis (stent) para drenaje?", text: "Colangiopancreatografía retrógrada endoscópica (CPRE) con [Esfinterotomía / Extracción de cálculos / Inserción de stent biliar / Fines exclusivamente diagnósticos].", code: "0F7...", tree: true },
    { type: "Procedimiento Omitido", terms: "ecg|electrocardiograma|electro", alert: "Prueba diagnóstica de rutina explícitamente excluida del CMBD. No requiere codificación.", text: "[NO PRECISA CODIFICACIÓN]", code: "[RUTINA]", tree: false },
    { type: "Procedimiento Omitido", terms: "sondaje vesical|sonda foley|cateterismo vesical", alert: "Procedimiento rutinario excluido del CMBD (salvo complicación mecánica o infecciosa explícita).", text: "[NO PRECISA CODIFICACIÓN]", code: "[RUTINA]", tree: false },
    { type: "Procedimiento Omitido", terms: "via periferica|cateter venoso periferico|abocath", alert: "Procedimiento rutinario excluido. Solo se codifican los accesos venosos centrales (CVC, PICC, Reservorio).", text: "[NO PRECISA CODIFICACIÓN]", code: "[RUTINA]", tree: false },
    { type: "Procedimiento Omitido", terms: "sng|sonda nasogastrica|sondaje nasogastrico", alert: "Procedimiento excluido del CMBD en hospitalización médica convencional.", text: "[NO PRECISA CODIFICACIÓN]", code: "[RUTINA]", tree: false }
];

// Rebuild medicalData from CSV items + Dynamic Trees
const medicalData = rawCsvData.map((item, index) => {
    let mappedType = item.tree ? 'tree_placeholder' : 'simple';
    if (item.type === 'Procedimiento Omitido') {
        mappedType = 'excluded';
    }

    const medicalItem = {
        id: `csv_${index}`,
        terms: item.terms.split('|'),
        type: mappedType,
        value: item.text,
        alert: item.alert,
        isFromCsv: true
    };

    if (item.tree) {
        injectDynamicTree(medicalItem);
    }

    return medicalItem;
});

/**
 * Parses bracketed options [Option A / Option B] from normative text
 * and translates them into an interactive decision tree object.
 */
function injectDynamicTree(item) {
    const template = item.value;
    const regex = /\[([^\]]+)\]/g;
    let match;

    const brackets = [];
    const allOptions = [];

    while ((match = regex.exec(template)) !== null) {
        const fullBracket = match[0];
        const content = match[1];

        // Ensure it contains multiple choice options (indicated by '/')
        if (content.includes('/')) {
            brackets.push(fullBracket);
            allOptions.push(content.split('/').map(s => s.trim()));
        }
    }

    if (allOptions.length === 0) {
        return; // Leave as tree_placeholder or simple
    }

    item.type = 'tree';
    item.root = buildNode(template, brackets, allOptions, 0);
}

function buildNode(currentTemplate, brackets, allOptions, level) {
    if (level >= allOptions.length) return null;

    const currentOptions = allOptions[level];
    const isLastLevel = level === allOptions.length - 1;

    const treeOptions = currentOptions.map(opt => {
        const newTemplate = currentTemplate.replace(brackets[level], opt);
        if (isLastLevel) {
            return { label: opt, value: newTemplate };
        } else {
            const nextNode = buildNode(newTemplate, brackets, allOptions, level + 1);
            return { label: opt, next: nextNode };
        }
    });

    return {
        question: "Seleccione opción:",
        options: treeOptions
    };
}
