const fs = require('fs');
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<!DOCTYPE html><html><body><input id="searchInput" /><div id="resultsContainer"></div><div id="errorLog"></div></body></html>`);
global.document = dom.window.document;
global.window = dom.window;

// Load the OFFLINE arrays
const dataCode = fs.readFileSync('data.js', 'utf8');
let appCode = fs.readFileSync('app.js', 'utf8');

eval(dataCode); // injects medicalData
eval(appCode);  // injects handleSearch, renderResultCard, etc.

function queryAndCount(q) {
    document.getElementById('resultsContainer').innerHTML = '';
    handleSearch(q);
    return document.getElementById('resultsContainer').children.length;
}

function getFirstResultTitle(q) {
    document.getElementById('resultsContainer').innerHTML = '';
    handleSearch(q);
    const container = document.getElementById('resultsContainer');
    if (container.children.length === 0) return null;
    return container.children[0].querySelector('.result-title').textContent.trim();
}

function verifyTreeButtons(q, expectedButtons) {
    document.getElementById('resultsContainer').innerHTML = '';
    handleSearch(q);
    const container = document.getElementById('resultsContainer');
    if (container.children.length === 0) return false;

    // Look for button elements generated by the tree logic
    const buttons = container.children[0].querySelectorAll('.btn-decision');
    const buttonTexts = Array.from(buttons).map(b => b.textContent.trim());

    // check if all expected buttons exist
    return expectedButtons.every(eb => buttonTexts.includes(eb));
}

let passed = true;
function assert(condition, message) {
    if (!condition) {
        console.error("❌ FAIL: " + message);
        passed = false;
    } else {
        console.log("✅ PASS: " + message);
    }
}

console.log("=== STARTING EXHAUSTIVE JS FRONTEND TESTS ===");

try {
    // 1. Edge Case: Word order completely scrambled
    assert(getFirstResultTitle('agudo confusional sindrome') === 'DELIRIUM', "Word order agnosticism failed for SCA");

    // 2. Edge Case: Handling exclusions
    assert(queryAndCount('sondaje vesical') === 1, "Exclusions duplicate removal failed");

    // 3. UI Path: Complex Tree rendering (Paracentesis)
    // Paracentesis should have Fin: [Diagnóstico / Terapéutico]
    assert(getFirstResultTitle('paracentesis') === 'PARACENTESIS', "Paracentesis query didn't return paracentesis as top result");
    assert(verifyTreeButtons('paracentesis', ['Diagnósticos', 'Terapéuticos']), "Tree buttons for Paracentesis didn't render correctly");

    // 4. UI Path: Neumonia tree fix
    // Was broken in CSV initially, now should generate "Hipoxémica" / "Hipercápnica" buttons
    assert(verifyTreeButtons('neumonia', ['Hipoxémica', 'Hipercápnica']), "Pneumonia buttons failed to render (tree fix failed)");

    // 5. Short queries should abort
    assert(queryAndCount('a') === 0, "1-char query didn't abort early");

    // 6. Fuzzy tolerance test (with scrambled order)
    // "fala hpatca" -> "falla hepatica"
    assert(getFirstResultTitle('fala hpatca') === 'FALLA HEPATICA AGUDA', "Fuzzy unscrambled match failed");

} catch (e) {
    console.error("Test execution threw a catastrophic error: ", e);
    passed = false;
}

if (passed) {
    console.log("\n🚀 ALL EXTENDED FRONTEND TESTS PASSED SUCCESSFULLY.");
} else {
    process.exit(1);
}
